-- 将索引表达式转成字符串
CREATE OR REPLACE FUNCTION  INDEX_COLUMN_EXPRESSION(
    IN_TABLE_NAME VARCHAR2,
    IN_INDEX_NAME VARCHAR2,
    IN_COLUMN_POSITION VARCHAR2
)
RETURN VARCHAR AS
    TEXT_STR VARCHAR2(32767);
    SQL_STR VARCHAR2(2000);
BEGIN
    SQL_STR = 'SELECT COLUMN_EXPRESSION
        FROM USER_IND_EXPRESSIONS T WHERE T.TABLE_NAME ='''|| IN_TABLE_NAME||'''
        AND T.INDEX_NAME = '''|| IN_INDEX_NAME||'''
        AND T.COLUMN_POSITION = '''|| IN_COLUMN_POSITION||''' ';
    EXECUTE IMMEDIATE SQL_STR INTO TEXT_STR;
    TEXT_STR := SUBSTR(TEXT_STR, 1,32767);
    RETURN TEXT_STR;
END;
/
-- ORACLE LONG 转 CHAR 函数
CREATE OR REPLACE FUNCTION LONG_TO_CHAR(
    IN_COLUMN_NAME VARCHAR2,
    IN_OWNER VARCHAR2,
    IN_INDEX_NAME VARCHAR2,
    IN_CONDITION VARCHAR2
)
    RETURN VARCHAR AS
    TEXT_STR VARCHAR2(32767);
    SQL_STR  VARCHAR2(2000);
BEGIN
    SQL_STR := 'SELECT ' || IN_COLUMN_NAME || ' FROM ' || IN_OWNER || '.' || IN_INDEX_NAME ||
               ' T WHERE 1=1 ' || IN_CONDITION;
    EXECUTE IMMEDIATE SQL_STR INTO TEXT_STR;
    TEXT_STR := SUBSTR(TEXT_STR, 1, 32767);
    RETURN TEXT_STR;
END;
/


