server:
  port: 31006
  servlet:
    context-path: /


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: your-username
    password: your-password
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      validation-query: SELECT 1
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin